Propositions
fsestini/tt-lecture-notes pull request #3
Opened 2017-03-22 21:52 UTC by mdipirro

2017-03-22 22:59 UTC, fsestini commented
@Oghma hai roba da aggiungere sulle proposizioni?

2017-03-22 23:10 UTC, Oghma commented
Si manca la mia parte che devo scrivere.

2017-03-22 23:38 UTC, fsestini requested changes
Aspettiamo @Oghma

2017-03-23 19:13 UTC, fsestini approved these changes

2017-03-23 19:13 UTC, merged